import * as THREE from 'three';

const root=document.getElementById('game');
const scene=new THREE.Scene();
scene.background=new THREE.Color(0x9ab9c2);scene.fog=new THREE.Fog(0x9ab9c2,45,190);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,300);camera.position.set(0,5.8,10.5);camera.lookAt(0,2,-28);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;root.appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xeaf7ff,0x3b342c,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe4b0,4);sun.position.set(-25,45,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-15;scene.add(sun);
const world=new THREE.Group();scene.add(world);
const mats={road:new THREE.MeshStandardMaterial({color:0x30383b,roughness:.92}),side:new THREE.MeshStandardMaterial({color:0x65716f,roughness:1}),rail:new THREE.MeshStandardMaterial({color:0xb7b7ad,metalness:.65,roughness:.35}),wood:new THREE.MeshStandardMaterial({color:0x624e38,roughness:1}),yellow:new THREE.MeshStandardMaterial({color:0xffcf26,roughness:.45}),red:new THREE.MeshStandardMaterial({color:0xd74632,roughness:.48}),blue:new THREE.MeshStandardMaterial({color:0x21758a,roughness:.3}),glass:new THREE.MeshStandardMaterial({color:0xb9e5e8,roughness:.12,metalness:.15}),dark:new THREE.MeshStandardMaterial({color:0x1c2529,roughness:.6}),skin:new THREE.MeshStandardMaterial({color:0xe7aa82,roughness:.75}),shirt:new THREE.MeshStandardMaterial({color:0xef4c35,roughness:.7}),pants:new THREE.MeshStandardMaterial({color:0x283746,roughness:.7}),shoe:new THREE.MeshStandardMaterial({color:0xf2f3ed,roughness:.65})};
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o};
const cyl=(r,h,m,seg=16)=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),m);o.castShadow=true;o.receiveShadow=true;return o};
function makeTrack(z){const g=new THREE.Group();const bed=box(15,.35,28,mats.road);bed.position.set(0,-.22,z);g.add(bed);for(const x of[-2.2,2.2]){const rail=box(.12,.12,28,mats.rail);rail.position.set(x,-.02,z);g.add(rail)}for(let i=-13;i<=13;i++){const sleeper=box(6.2,.12,.32,mats.wood);sleeper.position.set(0,-.06,z+i);g.add(sleeper)}return g}
for(let i=0;i<10;i++)world.add(makeTrack(-i*28));
function scenery(z){const g=new THREE.Group();for(const x of[-10,-15,10,15]){const h=5+Math.random()*14,w=4+Math.random()*6,b=box(w,h,5,new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.54,.18,.18+Math.random()*.14),roughness:.9}));b.position.set(x,h/2-1,z+(Math.random()-.5)*9);g.add(b);for(let y=2;y<h-1;y+=2.3){const win=box(.55,.65,.08,new THREE.MeshStandardMaterial({color:0xffd87a,emissive:0xffa32a,emissiveIntensity:.35}));win.position.set(x+(x>0?-w/2-.03:w/2+.03),y,b.position.z+.2);g.add(win)}}return g}
for(let i=0;i<18;i++)world.add(scenery(-i*18-20));
function lamp(z,x){const g=new THREE.Group();const pole=box(.12,4.8,.12,mats.dark);pole.position.y=2.2;g.add(pole);const arm=box(1.2,.12,.12,mats.dark);arm.position.set(x>0?-0.5:.5,4.55,0);g.add(arm);const light=new THREE.PointLight(0xffd98b,2,10);light.position.set(x>0?-1:.1,4.3,0);g.add(light);return g}
for(let i=0;i<20;i++){const z=-i*12-5;const l=lamp(z,-1);l.position.x=-5.2;world.add(l);const r=lamp(z,1);r.position.x=5.2;world.add(r)}
const player=new THREE.Group();scene.add(player);const torso=box(1.05,1.55,.65,mats.shirt);torso.position.y=2.15;player.add(torso);const head=cyl(.42,.72,mats.skin,20);head.rotation.x=Math.PI/2;head.position.y=3.25;player.add(head);const hair=cyl(.44,.25,mats.dark,20);hair.rotation.x=Math.PI/2;hair.position.y=3.55;player.add(hair);const leg1=box(.36,1.2,.42,mats.pants),leg2=leg1.clone();leg1.position.set(-.27,.78,0);leg2.position.set(.27,.78,0);player.add(leg1,leg2);const shoe1=box(.5,.22,.72,mats.shoe),shoe2=shoe1.clone();shoe1.position.set(-.27,.16,-.12);shoe2.position.set(.27,.16,-.12);player.add(shoe1,shoe2);const arm1=box(.3,1.25,.34,mats.shirt),arm2=arm1.clone();arm1.position.set(-.72,2.2,0);arm2.position.set(.72,2.2,0);player.add(arm1,arm2);player.position.set(0,0,5);player.traverse(o=>{if(o.isMesh)o.castShadow=true});
const board=box(2.25,.1,.48,new THREE.MeshStandardMaterial({color:0xffbd25,metalness:.2,roughness:.35}));board.position.y=.12;board.visible=false;player.add(board);
let playing=false,last=performance.now(),lane=1,targetLane=1,jump=0,roll=0,boardTime=0,score=0,coins=0,distance=0,speed=16,best=+(localStorage.metro3DBest||0),spawn=0,coinSpawn=0,powerSpawnT=5,power=null,powerLeft=0,objects=[],particles=[];
const $=id=>document.getElementById(id);$('best').textContent=best.toLocaleString();
function laneX(l){return(l-1)*2.2}
function reset(){playing=true;lane=targetLane=1;jump=roll=boardTime=score=coins=distance=0;speed=16;spawn=.7;coinSpawn=.4;powerSpawnT=5;power=null;powerLeft=0;objects.forEach(o=>world.remove(o.mesh));objects=[];particles.forEach(o=>scene.remove(o));particles=[];player.position.set(0,0,5);board.visible=false;$('start').classList.add('hidden');$('gameover').classList.add('hidden');last=performance.now()}
function makeTrain(){const g=new THREE.Group();const body=box(3.1,4.3,8,mats.red);body.position.y=2.15;g.add(body);const front=box(2.35,1.15,.18,mats.blue);front.position.set(0,3.1,4.1);g.add(front);for(const x of[-.78,.78]){const w=box(.9,.72,.15,mats.glass);w.position.set(x,3.15,4.2);g.add(w)}const stripe=box(3.15,.38,8,mats.yellow);stripe.position.y=2.2;g.add(stripe);for(const x of[-1.05,1.05]){const wh=cyl(.38,.3,mats.dark,18);wh.rotation.z=Math.PI/2;wh.position.set(x,.42,0);g.add(wh)}return g}
function makeBarrier(){const g=new THREE.Group();const b=box(3.2,1.35,.75,mats.red);b.position.y=.68;g.add(b);const stripe=box(2.8,.22,.8,mats.yellow);stripe.position.y=.72;g.add(stripe);for(const x of[-1.2,1.2]){const p=box(.16,1.5,.16,mats.dark);p.position.set(x,.55,0);g.add(p)}return g}
function makeLow(){const g=new THREE.Group();const b=box(3.4,.65,.75,mats.yellow);b.position.y=1.55;g.add(b);for(const x of[-1.35,1.35]){const p=box(.16,2,.16,mats.dark);p.position.set(x,.85,0);g.add(p)}return g}
function makeCoin(){const m=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.12,20),new THREE.MeshStandardMaterial({color:0xffd21f,metalness:.7,roughness:.22,emissive:0x6a4500}));m.rotation.z=Math.PI/2;m.castShadow=true;return m}
function makePower(type){const color={magnet:0x4dd8ff,jetpack:0xff673d,sneakers:0x69e86b,x2:0xffc51c}[type];const g=new THREE.Group();const s=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,1),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.25,metalness:.2,roughness:.3}));g.add(s);return g}
function spawnObj(type,l,z=-100){let mesh=type==='train'?makeTrain():type==='barrier'?makeBarrier():type==='low'?makeLow():type==='coin'?makeCoin():makePower(type);mesh.position.set(laneX(l),type==='coin'?1.5:0,z);world.add(mesh);objects.push({type,l,z,mesh,spin:Math.random()*6})}
function pattern(){const safe=Math.floor(Math.random()*3),r=Math.random();if(r<.3){for(let l=0;l<3;l++)if(l!==safe)spawnObj(Math.random()<.65?'train':'barrier',l)}else if(r<.52){const l=Math.floor(Math.random()*3);spawnObj('train',l);spawnObj('barrier',(l+1)%3,-115)}else if(r<.72)spawnObj(Math.random()<.5?'barrier':'low',Math.floor(Math.random()*3));else{const l=Math.floor(Math.random()*3);spawnObj('train',l);spawnObj('train',Math.floor(Math.random()*3),-120)}}
function coinLine(){const l=Math.floor(Math.random()*3);for(let i=0;i<7;i++)spawnObj('coin',l,-85-i*8)}
function power(){const types=['magnet','jetpack','sneakers','x2'];spawnObj(types[Math.floor(Math.random()*4)],Math.floor(Math.random()*3),-95)}
function control(c){if(!playing)return;if(c==='left')targetLane=Math.max(0,targetLane-1);if(c==='right')targetLane=Math.min(2,targetLane+1);if(c==='jump'&&jump<=0&&!roll&&!power)jump=.8;if(c==='roll'&&jump<=0&&!power)roll=.58;if(c==='board'&&boardTime<=0){boardTime=8;board.visible=true}}
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')control('left');if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')control('right');if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')control('jump');if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')control('roll');if(e.key===' ')control('board')});
let sx=0,sy=0;renderer.domElement.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});renderer.domElement.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<30)control('board');else if(Math.abs(dx)>Math.abs(dy))control(dx>0?'right':'left');else control(dy<0?'jump':'roll')},{passive:true});
function collect(o){if(o.type==='coin'){coins++;score+=power==='x2'?200:100;return true}if(['magnet','jetpack','sneakers','x2'].includes(o.type)){power=o.type;powerLeft=8;return true}return false}
function finish(){if(!playing)return;playing=false;const f=Math.floor(score),old=best;best=Math.max(best,f);localStorage.metro3DBest=best;$('finalScore').textContent=f.toLocaleString();$('finalCoins').textContent=coins.toLocaleString();$('finalDistance').textContent=Math.floor(distance)+'m';$('best').textContent=best.toLocaleString();$('newBest').classList.toggle('hidden',f<=old);$('gameover').classList.remove('hidden');$('flash').style.opacity=.28;setTimeout(()=>$('flash').style.opacity=0,90)}
function update(dt){distance+=speed*dt;score+=speed*dt*(power==='x2'?12:6);speed=Math.min(34,speed+dt*.32);lane+= (targetLane-lane)*Math.min(1,dt*13);player.position.x=laneX(lane);if(jump>0){jump=Math.max(0,jump-dt);const p=1-jump/.8;player.position.y=Math.sin(p*Math.PI)*4.1}else player.position.y=0;if(roll>0)roll=Math.max(0,roll-dt);player.rotation.z=(targetLane-lane)*-.16;player.rotation.x=roll?-.8:0;boardTime=Math.max(0,boardTime-dt);board.visible=boardTime>0;if(power){powerLeft-=dt;if(powerLeft<=0)power=null}spawn-=dt;coinSpawn-=dt;powerSpawnT-=dt;if(spawn<=0){pattern();spawn=.72+Math.random()*.42-Math.min(.2,(speed-16)*.012)}if(coinSpawn<=0){coinLine();coinSpawn=.9+Math.random()*.7}if(powerSpawnT<=0){power();powerSpawnT=9+Math.random()*8}
for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.z+=speed*dt;o.mesh.position.z=o.z;o.mesh.rotation.y+=dt*2;if(o.type==='coin'||['magnet','jetpack','sneakers','x2'].includes(o.type)){o.mesh.position.y=(o.type==='coin'?1.5:1.8)+Math.sin(performance.now()*.004+o.spin)*.18}
if(o.z>1&&o.z<9&&Math.abs(o.l-targetLane)<.35){if(o.type==='coin'||['magnet','jetpack','sneakers','x2'].includes(o.type)){if(o.type==='coin'&&power==='magnet'&&Math.abs(o.l-targetLane)<1.5){}if(collect(o)){world.remove(o.mesh);objects.splice(i,1);continue}}else{const safe=(o.type==='low'&&roll>0)||(o.type!=='low'&&jump>0)||(boardTime>0)||(power==='jetpack');if(!safe){if(boardTime>0){boardTime=0}else{finish();return}}else{world.remove(o.mesh);objects.splice(i,1);continue}}}if(o.z>18){world.remove(o.mesh);objects.splice(i,1)}}
if(power==='magnet'){for(const o of objects)if(o.type==='coin'&&o.z>0){o.l=targetLane;o.mesh.position.x=laneX(targetLane)}}
$('distance').textContent=Math.floor(distance);$('score').textContent=Math.floor(score).toLocaleString();$('coins').textContent=coins.toLocaleString();if(power){$('powerHud').classList.remove('hidden');$('powerName').textContent=power.toUpperCase();$('powerIcon').textContent={magnet:'🧲',jetpack:'🚀',sneakers:'👟',x2:'2×'}[power];$('powerBar').style.width=(powerLeft/8*100)+'%'}else $('powerHud').classList.add('hidden');
const targetZ=player.position.z-18;camera.position.x+=(player.position.x*.18-camera.position.x)*dt*4;camera.position.y+=(5.6+player.position.y*.22-camera.position.y)*dt*4;camera.position.z+=(10.5-camera.position.z)*dt*4;camera.lookAt(player.position.x*.15,2.0,targetZ);}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(playing)update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}
$('play').onclick=reset;$('again').onclick=reset;$('home').onclick=()=>{$('gameover').classList.add('hidden');$('start').classList.remove('hidden')};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8))});
requestAnimationFrame(loop);