const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=0,H=0,DPR=1,playing=false,last=0,elapsed=0,runSpeed=0.42,distance=0,score=0,coins=0,lane=1,targetLane=1,jump=0,roll=0,board=0,boardTime=0,objects=[],particles=[],shake=0,spawnTimer=0,coinTimer=0,powerTimer=0,power=null,powerLeft=0,best=Number(localStorage.metroRushBest||0),runId=0;
const $=id=>document.getElementById(id);
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function ease(t){return t*t*(3-2*t)}
function reset(){playing=true;elapsed=0;runSpeed=.42;distance=score=coins=0;lane=targetLane=1;jump=roll=board=boardTime=0;objects=[];particles=[];shake=0;spawnTimer=.55;coinTimer=.25;powerTimer=4;power=null;powerLeft=0;runId++;$('start').classList.add('hidden');$('gameover').classList.add('hidden');$('newBest').classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function finish(){if(!playing)return;playing=false;const final=Math.floor(score),old=best;best=Math.max(best,final);localStorage.metroRushBest=best;$('finalScore').textContent=final.toLocaleString();$('finalCoins').textContent=coins.toLocaleString();$('finalDistance').textContent=Math.floor(distance)+'m';$('best').textContent=best.toLocaleString();$('newBest').classList.toggle('hidden',final<=old);$('gameover').classList.remove('hidden');flash();}
function flash(){let a=0;const f=()=>{a+=.08;$('flash').style.opacity=Math.max(0,.32-a);if(a<.32)requestAnimationFrame(f)};f()}
function zY(z){return lerp(H*.19,H*.91,ease(z))}function roadHalf(z){return lerp(Math.min(W*.17,190),W*.49,ease(z))}function laneX(l,z){return W/2+(l-1)*roadHalf(z)*.58}function scaleZ(z){return lerp(.14,1.28,ease(z))}
function spawn(type,l=null,z=-.04){objects.push({type,l:l===null?Math.floor(Math.random()*3):l,z,spin:Math.random()*6.28,variant:Math.random()})}
function pattern(){const r=Math.random();if(r<.22){const safe=Math.floor(Math.random()*3);for(let l=0;l<3;l++)if(l!==safe)spawn(Math.random()<.72?'train':'barrier',l)}else if(r<.43){const l=Math.floor(Math.random()*3);spawn('train',l);spawn('barrier',(l+1)%3,-.13)}else if(r<.62){spawn('barrier',Math.floor(Math.random()*3));}else if(r<.76){spawn('low',Math.floor(Math.random()*3))}else if(r<.88){spawn('train',Math.floor(Math.random()*3));spawn('train',Math.floor(Math.random()*3),-.22)}else{const l=Math.floor(Math.random()*3);spawn('barrier',l);spawn('low',(l+1)%3,-.12);}}
function coinLine(){const l=Math.floor(Math.random()*3),count=5+Math.floor(Math.random()*6);for(let i=0;i<count;i++)spawn('coin',l,-.12-i*.105)}
function powerSpawn(){const types=['magnet','jetpack','sneakers','x2'];spawn(types[Math.floor(Math.random()*types.length)],Math.floor(Math.random()*3),-.05)}
function control(c){if(!playing)return;if(c==='left')targetLane=clamp(targetLane-1,0,2);if(c==='right')targetLane=clamp(targetLane+1,0,2);if(c==='jump'&&jump<=0&&!roll&&!power){jump=.78}if(c==='roll'&&jump<=0&&!power){roll=.58}if(c==='board'){if(board<=0){board=1;boardTime=8;}}}
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')control('left');if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')control('right');if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')control('jump');if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')control('roll');if(e.key===' ')control('board')});
let sx=0,sy=0;canvas.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});canvas.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<28)control('board');else if(Math.abs(dx)>Math.abs(dy))control(dx>0?'right':'left');else control(dy<0?'jump':'roll')},{passive:true});
function addParticle(x,y,vx,vy,color,life=1,size=3){particles.push({x,y,vx,vy,color,life,max:life,size})}
function coinBurst(x,y){for(let i=0;i<7;i++){const a=Math.random()*Math.PI*2,s=Math.random()*100+40;addParticle(x,y,Math.cos(a)*s,Math.sin(a)*s,'#ffd329',.45,Math.random()*3+2)}}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#142f49');g.addColorStop(.46,'#3d7180');g.addColorStop(1,'#d39c71');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const sunX=W*.72,sunY=H*.19;const sg=ctx.createRadialGradient(sunX,sunY,5,sunX,sunY,H*.24);sg.addColorStop(0,'#fff6c9aa');sg.addColorStop(1,'#fff0c900');ctx.fillStyle=sg;ctx.fillRect(0,0,W,H*.55);
ctx.fillStyle='#18313b99';for(let i=0;i<20;i++){const bw=30+(i*19)%70,bh=25+(i*37)%125,bx=(i*83)%W;ctx.fillRect(bx,H*.31-bh,bw,bh)}
ctx.fillStyle='#23434c';ctx.beginPath();ctx.moveTo(0,H*.33);ctx.lineTo(W*.18,H*.27);ctx.lineTo(W*.36,H*.34);ctx.lineTo(W*.55,H*.25);ctx.lineTo(W*.75,H*.33);ctx.lineTo(W,H*.28);ctx.lineTo(W,H*.43);ctx.lineTo(0,H*.43);ctx.fill()}
function drawRoad(){const hz=H*.19,bot=H*.95,hw=roadHalf(1);ctx.fillStyle='#252d32';ctx.beginPath();ctx.moveTo(W/2-hw,hz);ctx.lineTo(W/2+hw,hz);ctx.lineTo(W,bot);ctx.lineTo(0,bot);ctx.fill();
ctx.fillStyle='#3b454a';ctx.beginPath();ctx.moveTo(W/2-hw*.85,hz);ctx.lineTo(W/2+hw*.85,hz);ctx.lineTo(W*.95,bot);ctx.lineTo(W*.05,bot);ctx.fill();
for(let i=0;i<25;i++){const z=((i*.115+elapsed*runSpeed*1.55)%1),y=zY(z),half=roadHalf(z);ctx.strokeStyle='#d9d1bd';ctx.lineWidth=Math.max(1,3*z);ctx.beginPath();ctx.moveTo(W/2-half,y);ctx.lineTo(W/2+half,y);ctx.stroke()}
for(let l=1;l<3;l++){ctx.strokeStyle='#9a9689aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W/2+(l-1.5)*roadHalf(0)*.58,hz);ctx.lineTo(W/2+(l-1.5)*roadHalf(1)*.58,bot);ctx.stroke()}}
function drawPole(x,y,s){ctx.strokeStyle='#151b20';ctx.lineWidth=5*s;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-H*.28*s);ctx.stroke();ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(x-H*.045*s,y-H*.25*s);ctx.lineTo(x+H*.045*s,y-H*.25*s);ctx.stroke()}
function drawTrain(o){const s=scaleZ(o.z),x=laneX(o.l,o.z),y=zY(o.z),w=75*s,h=120*s;ctx.save();ctx.translate(x,y-h*.5);ctx.fillStyle='#c94b35';ctx.fillRect(-w/2,-h/2,w,h);ctx.fillStyle='#1b6570';ctx.fillRect(-w*.39,-h*.28,w*.78,h*.25);ctx.fillStyle='#a7d9d8';ctx.fillRect(-w*.33,-h*.25,w*.28,h*.17);ctx.fillRect(w*.05,-h*.25,w*.28,h*.17);ctx.fillStyle='#e9b52d';ctx.fillRect(-w*.46,-h*.02,w*.92,h*.09);ctx.fillStyle='#252a2e';ctx.fillRect(-w*.45,h*.19,w*.9,h*.11);ctx.fillStyle='#111';ctx.fillRect(-w*.33,h*.31,w*.18,h*.18);ctx.fillRect(w*.15,h*.31,w*.18,h*.18);ctx.restore()}
function drawBarrier(o){const s=scaleZ(o.z),x=laneX(o.l,o.z),y=zY(o.z),w=76*s,h=45*s;ctx.save();ctx.translate(x,y);ctx.fillStyle='#db4a37';ctx.fillRect(-w/2,-h,w,h);ctx.fillStyle='#ffd329';ctx.fillRect(-w*.43,-h*.76,w*.86,h*.14);ctx.fillStyle='#232a2d';ctx.fillRect(-w*.42,-h*.42,w*.84,h*.12);ctx.fillStyle='#111820';ctx.fillRect(-w*.42,-h*.02,w*.14,h*.12);ctx.fillRect(w*.28,-h*.02,w*.14,h*.12);ctx.restore()}
function drawLow(o){const s=scaleZ(o.z),x=laneX(o.l,o.z),y=zY(o.z),w=86*s,h=30*s;ctx.save();ctx.translate(x,y-h*1.9);ctx.fillStyle='#e1a72b';ctx.fillRect(-w/2,0,w,h);ctx.fillStyle='#293338';ctx.fillRect(-w*.42,h*.18,w*.84,h*.25);ctx.fillStyle='#dce5df';ctx.fillRect(-w*.35,h*.52,w*.7,h*.1);ctx.restore()}
function drawCoin(o){const s=scaleZ(o.z),x=laneX(o.l,o.z),y=zY(o.z)-38*s;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(elapsed*7+o.spin)*.55);ctx.scale(s,s);ctx.fillStyle='#ffd329';ctx.shadowColor='#ffd329';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff0a1';ctx.beginPath();ctx.arc(-4,-4,4,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPower(o){const s=scaleZ(o.z),x=laneX(o.l,o.z),y=zY(o.z)-48*s;const icons={magnet:'M',jetpack:'J',sneakers:'S',x2:'2X'};ctx.save();ctx.translate(x,y);ctx.rotate(elapsed*1.7);ctx.scale(s,s);ctx.fillStyle='#42c6ff';ctx.shadowColor='#42c6ff';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,20,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='900 10px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icons[o.type],0,1);ctx.restore()}
function drawPlayer(){const x=lerp(laneX(1,1),laneX(targetLane,1),1-Math.exp(-12*(1/60))),base=H*.78;let jy=0;if(jump>0){const p=1-jump/.78;jy=-Math.sin(p*Math.PI)*H*.19}const yy=base+jy,lean=(targetLane-lane)*.12;ctx.save();ctx.translate(x,yy);ctx.rotate(lean);if(board){ctx.fillStyle='#ffcc35';ctx.shadowColor='#ffcc35';ctx.shadowBlur=12;ctx.fillRect(-37,19,74,6);ctx.shadowBlur=0}if(power==='jetpack'){ctx.fillStyle='#ff743d';ctx.beginPath();ctx.moveTo(-13,18);ctx.lineTo(-3,45);ctx.lineTo(3,18);ctx.fill();ctx.beginPath();ctx.moveTo(13,18);ctx.lineTo(3,45);ctx.lineTo(-3,18);ctx.fill()}if(roll>0){ctx.rotate(-.25);ctx.scale(1.22,.64)}ctx.fillStyle='#e8a77f';ctx.beginPath();ctx.arc(0,-72,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1b2730';ctx.beginPath();ctx.arc(0,-79,19,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#ef4e35';ctx.fillRect(-17,-56,34,40);ctx.fillStyle='#f3d9b4';ctx.fillRect(-18,-16,14,33);ctx.fillRect(4,-16,14,33);ctx.fillStyle='#18242b';ctx.fillRect(-21,14,18,7);ctx.fillRect(3,14,18,7);if(board){ctx.strokeStyle='#8ae8ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-31,28);ctx.lineTo(-5,28);ctx.stroke()}ctx.restore()}
function drawObjects(){objects.slice().sort((a,b)=>a.z-b.z).forEach(o=>{if(o.z<0)return;if(o.type==='coin')drawCoin(o);else if(['magnet','jetpack','sneakers','x2'].includes(o.type))drawPower(o);else if(o.type==='train')drawTrain(o);else if(o.type==='low')drawLow(o);else drawBarrier(o)})}
function collect(o){if(o.type==='coin'){coins++;score+=100*(power==='x2'?2:1);coinBurst(laneX(o.l,o.z),zY(o.z)-30*scaleZ(o.z));return true}if(['magnet','jetpack','sneakers','x2'].includes(o.type)){power=o.type;powerLeft=7;powerTimer=9;return true}return false}
function collision(o){if(o.z<.84||o.z>1.02||Math.abs(o.l-targetLane)>.32)return false;if(o.type==='coin')return true;if(['magnet','jetpack','sneakers','x2'].includes(o.type))return true;if(board)return true;if(power==='jetpack')return true;if(o.type==='low')return roll<=0&&jump<=0;if(o.type==='barrier')return jump<=0&&roll<=0;return jump<=0&&roll<=0}
function update(dt){elapsed+=dt;runSpeed=Math.min(.86,runSpeed+dt*.012);distance+=dt*runSpeed*145;score+=dt*runSpeed*175*(power==='x2'?2:1);lane+=(targetLane-lane)*Math.min(1,dt*14);if(jump>0)jump=Math.max(0,jump-dt);if(roll>0)roll=Math.max(0,roll-dt);if(board){boardTime-=dt;if(boardTime<=0)board=0}if(power){powerLeft-=dt;if(powerLeft<=0)power=null;if(power==='magnet'){objects.forEach(o=>{if(o.type==='coin'&&o.z>.45){const d=o.l-targetLane;if(Math.abs(d)<1.1)o.l=targetLane}})}}spawnTimer-=dt;coinTimer-=dt;powerTimer-=dt;const gap=Math.max(.46,.98-runSpeed*.38);if(spawnTimer<=0){pattern();spawnTimer=gap*(.78+Math.random()*.42)}if(coinTimer<=0){coinLine();coinTimer=.72+Math.random()*.55}if(powerTimer<=0){powerSpawn();powerTimer=8+Math.random()*9}
for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.z+=dt*runSpeed*1.04;if(o.z>.88&&o.z<1.08&&Math.abs(o.l-targetLane)<.34){if(collect(o))objects.splice(i,1);else if(collision(o)){if(board){board=0;boardTime=0;shake=.3;objects.splice(i,1);for(let k=0;k<20;k++)addParticle(laneX(o.l,1),H*.76,(Math.random()-.5)*260,-Math.random()*240,'#ffd329',.5,3)}else{finish();return}}}if(o.z>1.15)objects.splice(i,1)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=380*dt;if(p.life<=0)particles.splice(i,1)}if(shake>0)shake-=dt;updateHud()}
function updateHud(){$('coins').textContent=coins.toLocaleString();$('score').textContent=Math.floor(score).toLocaleString();$('distance').textContent=Math.floor(distance).toLocaleString();$('best').textContent=best.toLocaleString();if(power){$('powerHud').classList.remove('hidden');const names={magnet:'COIN MAGNET',jetpack:'JETPACK',sneakers:'SUPER SNEAKERS',x2:'2X MULTIPLIER'};const icons={magnet:'M',jetpack:'J',sneakers:'S',x2:'2X'};$('powerName').textContent=names[power];$('powerIcon').textContent=icons[power];$('powerBar').style.width=(powerLeft/7*100)+'%'}else $('powerHud').classList.add('hidden')}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*10,(Math.random()-.5)*8);drawSky();drawRoad();for(let i=0;i<7;i++){const z=(i*.17+elapsed*runSpeed*.55)%1;drawPole(W*.07+W*.86*((i%2)/2),zY(z),.25+z*.8)}drawObjects();drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;ctx.restore()}
function loop(now){if(!playing)return;const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();if(playing)requestAnimationFrame(loop)}
$('play').onclick=reset;$('again').onclick=reset;$('home').onclick=()=>{$('gameover').classList.add('hidden');$('start').classList.remove('hidden')};best=Number(localStorage.metroRushBest||0);$('best').textContent=best.toLocaleString();draw();
